"""add title and category to chat_sessions

Revision ID: 06bbd4d3ce37
Revises: 3cafc9766261
Create Date: 2025-04-26 10:37:49.680770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06bbd4d3ce37'
down_revision: Union[str, None] = '3cafc9766261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('system_prompt', sa.Text(), nullable=True))
    op.add_column('chat_sessions', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('chat_sessions', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'category')
    op.drop_column('chat_sessions', 'title')
    op.drop_column('chat_sessions', 'system_prompt')
    # ### end Alembic commands ###
