"""adding due_date, reminder_at, reoccurance column in task table

Revision ID: 113bea588f26
Revises: 681d7367f73a
Create Date: 2025-05-12 13:45:38.242281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113bea588f26'
down_revision: Union[str, None] = '681d7367f73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('reminder_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('recurrence', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'recurrence')
    op.drop_column('tasks', 'reminder_at')
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###
