"""upgrading email, email_thread table

Revision ID: 18663271931d
Revises: 7fbfbb7ff705
Create Date: 2025-04-21 17:23:30.328100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18663271931d'
down_revision: Union[str, None] = '7fbfbb7ff705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_threads', sa.Column('last_email_id', sa.String(), nullable=True))
    op.add_column('email_threads', sa.Column('last_body_preview', sa.Text(), nullable=True))
    op.add_column('email_threads', sa.Column('total_count', sa.Integer(), nullable=True))
    op.add_column('email_threads', sa.Column('ccreated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'email_threads', 'emails', ['last_email_id'], ['id'])
    op.drop_column('email_threads', 'last_email_data')
    op.drop_column('email_threads', 'created_at')
    op.add_column('emails', sa.Column('sender_name', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('sent_at', sa.DateTime(), nullable=True))
    op.add_column('emails', sa.Column('web_link', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('message_id', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('importance', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'importance')
    op.drop_column('emails', 'message_id')
    op.drop_column('emails', 'web_link')
    op.drop_column('emails', 'sent_at')
    op.drop_column('emails', 'sender_name')
    op.add_column('email_threads', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('email_threads', sa.Column('last_email_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'email_threads', type_='foreignkey')
    op.drop_column('email_threads', 'ccreated_at')
    op.drop_column('email_threads', 'total_count')
    op.drop_column('email_threads', 'last_body_preview')
    op.drop_column('email_threads', 'last_email_id')
    # ### end Alembic commands ###
