"""updating small mistake in Email_thread table: ccreated_at --> created_at

Revision ID: 1e1d0ac5ceea
Revises: 18663271931d
Create Date: 2025-04-22 06:06:55.750863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e1d0ac5ceea'
down_revision: Union[str, None] = '18663271931d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_threads', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('email_threads', 'ccreated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_threads', sa.Column('ccreated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('email_threads', 'created_at')
    # ### end Alembic commands ###
