"""Adding Email Threads table

Revision ID: 38767ed63849
Revises: 5fe4dcfcfbc1
Create Date: 2025-04-07 09:56:27.032865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38767ed63849'
down_revision: Union[str, None] = '5fe4dcfcfbc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_threads',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('last_email_at', sa.DateTime(), nullable=True),
    sa.Column('last_sender', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('extracted_tasks', sa.Text(), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=True),
    sa.Column('is_processing', sa.Boolean(), nullable=True),
    sa.Column('last_email_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_threads')
    # ### end Alembic commands ###
