"""adding few columns in Email Threads table

Revision ID: 38d7a0188f3a
Revises: 06bbd4d3ce37
Create Date: 2025-05-08 21:40:02.117578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d7a0188f3a'
down_revision: Union[str, None] = '06bbd4d3ce37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_threads', sa.Column('last_sender_name', sa.String(), nullable=True))
    op.add_column('email_threads', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.add_column('email_threads', sa.Column('has_attachment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_threads', 'has_attachment')
    op.drop_column('email_threads', 'is_read')
    op.drop_column('email_threads', 'last_sender_name')
    # ### end Alembic commands ###
