"""adding new column 'attachment_url' in comment table

Revision ID: 48286824d42d
Revises: 4f58ca4e6a40
Create Date: 2025-03-30 10:18:30.766312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48286824d42d'
down_revision: Union[str, None] = '4f58ca4e6a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('attachment_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'attachment_url')
    # ### end Alembic commands ###
