"""updating small mistake in emails table: category  --> categories

Revision ID: 65160e0e0611
Revises: 1e1d0ac5ceea
Create Date: 2025-04-22 06:13:14.967906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65160e0e0611'
down_revision: Union[str, None] = '1e1d0ac5ceea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('categories', sa.String(), nullable=True))
    op.drop_column('emails', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('emails', 'categories')
    # ### end Alembic commands ###
