"""small update

Revision ID: 681d7367f73a
Revises: 38d7a0188f3a
Create Date: 2025-05-08 21:46:59.818250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '681d7367f73a'
down_revision: Union[str, None] = '38d7a0188f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_threads', sa.Column('has_attachments', sa.Boolean(), nullable=True))
    op.drop_column('email_threads', 'has_attachment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_threads', sa.Column('has_attachment', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('email_threads', 'has_attachments')
    # ### end Alembic commands ###
