"""Add last_synced_at to OutlookCredentials

Revision ID: 7fbfbb7ff705
Revises: 38767ed63849
Create Date: 2025-04-19 12:28:58.367174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fbfbb7ff705'
down_revision: Union[str, None] = '38767ed63849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outlook_credentials', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outlook_credentials', 'last_synced_at')
    # ### end Alembic commands ###
