"""Changing the coloumn of 'sender' in Email table

Revision ID: e240c92da256
Revises: f7a07893d5d5
Create Date: 2025-04-25 00:50:58.926687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e240c92da256'
down_revision: Union[str, None] = 'f7a07893d5d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('sender', sa.String(), nullable=False))
    op.drop_column('emails', 'sender_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('sender_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('emails', 'sender')
    # ### end Alembic commands ###
