"""Changing the coloumn of 'sender_email' in Email table

Revision ID: f7a07893d5d5
Revises: f7b05f62c712
Create Date: 2025-04-25 00:47:35.494810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a07893d5d5'
down_revision: Union[str, None] = 'f7b05f62c712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('sender_email', sa.String(), nullable=False))
    op.drop_column('emails', 'sender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('emails', 'sender_email')
    # ### end Alembic commands ###
